In [1]:
import pandas as pd

In [3]:
import datetime
print(f"Last updated: {datetime.datetime.now()}")

Last updated: 2023-12-07 07:01:10.491750


In [4]:
import numpy as np

In [5]:
print(np.__version__)



1.26.2


# 1. Data Types and Attributes

In [6]:
#the main type in numpy is ndarray, even seeminglydifferent kinds of arrays are still
#ndarray's. 

In [8]:
# 1 - dimensional array, also called a vector
a1 = np.array([1,2,3])
# 2 - dimensional array, also referred to as a matrix
a2 = np.array([[1,2.0,3.3],
               [4,5,6.5]])
# 3 - dimensional array also called a matrix as well. 
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
               [13,14,15],
               [16,17,18]]] )

In [9]:
a1.shape, a1.ndim, a1.dtype,a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [10]:
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('float64'), 6, numpy.ndarray)

In [11]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [12]:
a1

array([1, 2, 3])

In [13]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [14]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])


![](numpy-anatomy-of-an-array-updated.png)


In [34]:
#credit to MrdBourke for the image 

In [18]:
# Use ![](file path) to insert a photo 

In [19]:
#Key terms 

In [20]:
# Array = a list of numbers can be multi-deminsional

In [21]:
# Scalar = a single number

In [22]:
# Vector = a list of numbers with 1-dimension

In [23]:
# Matrix = A (usually) multi demensional list of numbers 

# Pandas DataFrame out of NumPy arrays

In [24]:
import pandas as pd

In [25]:
df = pd.DataFrame(np.random.randint(10, size=(5,3)),
                  columns=['a', 'b', 'c'])
df

a  b  c
0  8  3  4
1  6  7  3
2  5  5  5
3  3  1  8
4  9  2  0

In [26]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [27]:
df2 = pd.DataFrame(a2)
df2

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# Creating Arrays

In [47]:
#np.array()
simple_array = np.array([1,2,3])
simple_array, simple_array.dtype


(array([1, 2, 3]), dtype('int64'))

In [37]:
#np.ones()
ones= np.ones((10,2))
ones, ones.dtype #defautl data type is float64
#ones.astype(int) will change the tyep.

(array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]),
 dtype('float64'))

In [38]:
zeros = np.zeros((5,3,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [40]:
#An array with a range of values

In [43]:
range_array = np.arange(0, 10, 2)
range_array
#looking at the output it gives us an array that starts at 0, goes by 2's but stops 
#before 10

array([0, 2, 4, 6, 8])

In [46]:
range_array2 = np.arange(0,16,4)
range_array2
#lets try again. Looks lik the first number you pass is the beginnign number
#the second number is the upper range meaning it ends BEFORE that number
#the last number is how it invrements so this range will go by 4's

array([ 0,  4,  8, 12])

In [49]:
#random array
random_array = np.random.randint(10, size=(5,3))
random_array

array([[9, 5, 2],
       [9, 2, 6],
       [5, 1, 8],
       [0, 3, 8],
       [5, 1, 3]])

In [51]:
#looking at out array it has the size 5 rows 3 columns, and all the numbers are less
#than 10. Lets try another set up

In [53]:
random_array2 = np.random.randint(10, size = (15,2))
random_array2

array([[8, 6],
       [7, 7],
       [3, 8],
       [7, 4],
       [5, 2],
       [7, 6],
       [3, 4],
       [4, 4],
       [4, 4],
       [2, 7],
       [9, 5],
       [6, 1],
       [8, 3],
       [7, 0],
       [1, 0]])

In [55]:
#Random Floats between 0, 1
np.random.random((5,3))

array([[0.80174317, 0.38601999, 0.05853625],
       [0.18172649, 0.76612845, 0.57776808],
       [0.37618654, 0.28478245, 0.75257116],
       [0.14640062, 0.3029177 , 0.64185093],
       [0.26232606, 0.47806164, 0.49495982]])

In [59]:
#Random 5X3 array of floats similar to above
np.random.rand(5,3) # makes sure you pay attention to how the argument is doen

array([[0.77830154, 0.67735922, 0.96338264],
       [0.02088309, 0.51894293, 0.2580365 ],
       [0.55251137, 0.36435373, 0.54422858],
       [0.58268314, 0.20743141, 0.93382066],
       [0.91600469, 0.56925198, 0.49299174]])

In [ ]:
#numpy uses pseudo random numbers. Esentially they look random but are not. for consis